Emtags\Bundle\NewsletterBundle\Entity\Dispatches:
    type: entity
    table: dispatches
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        date:
            type: datetime
            nullable: false
    oneToOne:
        campaign:
            targetEntity: Campaigns
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                campaign_id:
                    referencedColumnName: id
            orphanRemoval: false
        lead:
            targetEntity: Leads
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                lead_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
