Emtags\Bundle\NewsletterBundle\Entity\Tags:
    type: entity
    table: tags
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 100
            fixed: false
            nullable: false
    manyToMany:
        lead:
            targetEntity: Leads
            cascade: {  }
            mappedBy: tag
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
